# Generated by Django 4.0.4 on 2022-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('종별', models.TextField(blank=True, null=True)),
                ('업소명', models.TextField(blank=True, null=True)),
                ('주소', models.TextField(blank=True, null=True)),
                ('전화번호', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
    ]
