# Generated by Django 4.0.3 on 2022-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('종별', models.TextField(blank=True, null=True)),
                ('업소명', models.TextField(blank=True, null=True)),
                ('주소', models.TextField(blank=True, null=True)),
                ('전화번호', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
