# Generated by Django 4.0.3 on 2022-05-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_test_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('주소', models.TextField(blank=True, null=True)),
                ('병원분류', models.TextField(blank=True, null=True)),
                ('병원분류명', models.TextField(blank=True, null=True)),
                ('응급의료기관코드명', models.TextField(blank=True, null=True)),
                ('응급실운영여부', models.TextField(blank=True, null=True)),
                ('기관명', models.TextField(blank=True, null=True)),
                ('대표전화1', models.TextField(blank=True, null=True)),
                ('응급실전화', models.TextField(blank=True, null=True)),
                ('월요진료', models.TextField(blank=True, null=True)),
                ('화요진료', models.TextField(blank=True, null=True)),
                ('수요진료', models.TextField(blank=True, null=True)),
                ('목요진료', models.TextField(blank=True, null=True)),
                ('금요진료', models.TextField(blank=True, null=True)),
                ('토요진료', models.TextField(blank=True, null=True)),
                ('일요진료', models.TextField(blank=True, null=True)),
                ('공휴일진료', models.TextField(blank=True, null=True)),
                ('기관ID', models.TextField(blank=True, db_column='기관ID', null=True)),
                ('병원경도', models.TextField(blank=True, null=True)),
                ('병원위도', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
