# Generated by Django 4.0.3 on 2022-05-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_normalh_delete_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='normalh',
            table='normalH',
        ),
    ]
